server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/cluster-issuer: ca-issuer
    ingressClassName: "nginx"
    hosts: 
      - argocd.k8s.intra
    tls:
      - secretName: argocd-tls-certificate
        hosts:
          - argocd.k8s.intra
    https: true
  additionalProjects:
    - name: system-apps
      namespace: argocd-system
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: https://kubernetes.default.svc
      syncWindows:
      - kind: allow
        schedule: '*/5 * * * *'
        manualSync: true
  additionalApplications:
    - name: system-apps
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      project: system-apps
      source:
        repoURL: https://github.com/devopstales/gitops_argocd
        targetRevision: HEAD
        path: apps
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
dex:
  enabled: false

configs:
  repositories:
    argo-cd-helm-repo:
      name: argo-cd-helm-repo
      type: helm
      url: https://argoproj.github.io/argo-helm
    private-repo:
      name: git-repo
      url: https://github.com/devopstales/gitops_argocd
      
#  secret:
#    argocdServerAdminPassword: "Password1"
